# Generated by Django 2.0.3 on 2018-03-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('website', models.URLField(verbose_name='website')),
                ('photo', models.FileField(upload_to='college')),
            ],
        ),
    ]
