# Generated by Django 2.0.3 on 2018-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[['Hello', 'Hello'], ['Folo', 'Folo'], ['Fr. Bandra', 'Fr. Bandra']], max_length=30),
        ),
    ]
