# Generated by Django 2.0.3 on 2018-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='photo',
            field=models.FileField(blank=True, upload_to='college'),
        ),
    ]
