# Generated by Django 2.0.3 on 2018-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180318_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>', unique=True),
        ),
    ]
