# Generated by Django 2.0.3 on 2018-04-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180412_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='College',
            field=models.CharField(blank=True, choices=[['Folo', 'Folo'], ['Fr. Bandra', 'Fr. Bandra'], ['Loking', 'Loking']], max_length=30),
        ),
    ]
