# Generated by Django 2.0.3 on 2018-04-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180412_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='college',
            new_name='college_name',
        ),
    ]
