# Generated by Django 2.0.3 on 2018-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180412_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_name',
            field=models.CharField(blank=True, choices=[['DJ Sanjvi', 'DJ Sanjvi'], ['Folo', 'Folo'], ['Fr. Bandra', 'Fr. Bandra'], ['Loking', 'Loking'], ['VIT', 'VIT'], ['pagal khaana', 'pagal khaana']], max_length=30),
        ),
    ]
