# Generated by Django 2.0.3 on 2018-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
